spring:
  application:
    name: admin-server
  profiles:
    active:
    - secure
  boot:
    admin:
      notify:
        mail:
          to: 15017263266@163.com  # 邮件接收方
          from: 911858173@qq.com  # 邮件发送方
  mail:
    host: smtp.qq.com   # qq邮箱服务器主机host，需要在QQ邮箱设置中开启smtp协议 163邮箱为smtp.163.com
    username: 911858173@qq.com  # qq邮箱账号
    password: nqylfjzcykkpbcch  # 第三方登录的授权码
    properties:
      mail.debug: false
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

# 2.0开始，actuator默认不开放，所以要设置为开发
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8000
# end::configuration-eureka[]

---
spring:
  profiles: insecure

---
# admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: "root"
      password: "root"

# 注册给eureka的时候告诉eureka自己的密码
eureka:
  instance:
    metadata-map:
      "user.name": ${spring.security.user.name}         #These two are needed so that the server
      "user.password": ${spring.security.user.password} #can access the protected client endpoints
